services:
  downloader:
    build: .

    container_name: platzi-downloader

    volumes:
      - ./downloads:/downloads
      - ./cookies:/cookies
      - .:/app

    stdin_open: true
    tty: true

    shm_size: "2gb"

    environment:
      - PYTHONUNBUFFERED=1

    restart: unless-stopped
